<?php 
	require_once("commonCode.php");
?>
<!DOCTYPE html>
<html>
<head>
	<title>Policy | Akib's News Portal</title>
	<link rel="stylesheet" type="text/css" href="CSS/commonCode.css">
	<link rel="stylesheet" type="text/css" href="CSS/policy.css">
</head>
<body>
	<div id="main_body" style="background-color: #ffffff;">
		<?php TITLE_LOGO(); ?>
		<?php NAVIGATION_BAR(); ?>
		<div id="policy_list">
		<div>
			<h4>Privacy Policy of <i>Akib's News Portal</i></h4>
			<p>Akib's News Portal is committed to protecting your personal information when you are 
				using the website of Akib's News Portal or an application developed by Akib's News Portal. 
				This privacy policy relates to use of any personal information that it collects 
				from visitors/readers via following, among other, services:
				<ul>
			    			<li>any Akib's News Portal website that links to this privacy and cookies policy;</li>
			    			<li>social media or official Akib's News Portal content on other websites;</li>
			    			<li>mobile device and/or applications (“Apps”)</li>
				</ul>
			</p>
			
			<p>In all the above services, the privacy policy shall apply only when the application,
			website or contents therein are generated by Akib's News Portal.</p>
			
			<p>Akib's News Portal collects or receives information about its users for many purposes; 
			for instance, to provide services designed to serve the user, to monitor and improve the
			services offerings, for marketing or targeting advertisement etc. Such information may 
			include your name, address, phone number, email address, age, social network account etc. 
			(“the Information”).</p>
			
			<p>There may be other privacy policies that apply to certain services provided by Akib's News Portal. Visitors are requested to read these while registering or subscribing to these
			services on these sites. It is Akib's News Portal’s endeavor to protect the information received 
			from its visitors/readers. Akib's News Portal respects privacy of its visitors/readers and makes 
			use its best effort to ensure that the information collected is used for the limited purpose 
			for which it was received.</p>
			
			<h4>How <i>Akib's News Portal</i> collects the information</h4>
			<p>Akib's News Portal collects information on a user upon the user’s access to the Akib's News Portal 
			website – (i) by registering to the site or application, (ii) subscribing to the newsletter, 
			(iii) responding to a survey or participating in a competition, (iv) logging in to a site or 
			page, etc.</p>
			
			<h4>Disclosure of Information Collected</h4>
			<p>Akib's News Portal does not sell, trade or otherwise provide personally identifiable
			information to any other parties except for those that assist Akib's News Portal in operating its
			website, conducting the business and serving the users. It may share visitor's/reader's 
			personal information internally to understand user base, promote the number of users and 
			increase user engagement.<br>
			In the event that Akib's News Portal desires to use personal information in a different way than 
			that described above it shall seek consent of the individual. Akib's News Portal may release 
			personally identifiable information if it is required to comply with the laws of Bangladesh.
			</p>
			
			<p>Notwithstanding anything contained in this privacy policy, Akib's News Portal may disclose or 
			share information collected including personal information to service providers, affiliate 
			companies, consultants or advisors or Partners that it has engaged to perform 
			business-related functions on its behalf. Akib's News Portal may also share the information in 
			response to legal process, or protect its interest in any forum. The information may be used 
			for investigating or preventing potentially illegal activities, or situations involving 
			potential threats to any person, us, or the services, or violations of our policies, the law 
			or our Terms of Use as well as to verify or enforce compliance with the policies governing 
			our Services. The information may as well be shared to offer market products or services to 
			the visitors/readers. However, in all these events or any other event when a personal 
			information is shared or disclosed, Akib's News Portal shall use its best endeavors to control 
			the share or disclosure and shall only share to such extent as it is required to meet the 
			purpose.</p>
			
			<h4>Data Retention</h4>
			<p>We shall hold visitors/readers personal information if your account exists with Bengal 
			Gazette. Notwithstanding, Akib's News Portal may retain data for a further period as per its own 
			internal data retention policy. Visitor's/reader's personal information shall be deleted upon 
			expiry of your Akib's News Portal account. Please note that there may be events when the erasing/
			deleting of information may take more time than usual, and Akib's News Portal shall not hold any 
			responsibility in such events.</p>
			
			<h4>Advertisement</h4>
			<p>The advertisements included in the Akib's News Portal website and mobile apps, are by 
			third-party companies & ad networks through independent ad tags, which may collect 
			information about users for which Akib's News Portal shall bear no responsibility that may arise 
			as a result of collecting and/or sharing the information’s with any other party.<br>
			Akib's News Portal shall not accept any liability that may arise as a result of any content of
			any advertisement that may appear on the Akib's News Portal website.</p>
			
			<h4>Third Party Advertisements and links</h4>
			<p>At the discretion of Akib's News Portal, the website or application may display or allow
			advertisements of third party services or products. These third-party sites may have separate 
			and independent privacy policies. Akib's News Portal accepts no responsibility or liability for 
			the content of advertising material, including, without limitation, any error, omission or 
			inaccuracy therein.<br>
			Akib's News Portal does not hold any responsibility for information leakage due to the visitor/
			reader accessing to a separate link, application or website, whether through a link in the 
			website or contents of Akib's News Portal.</p>
			
			<h4>Use of Cookies</h4>
			<p>Akib's News Portal does not collect any user data based on cookies, neither does it store any
			sort of user information that may be personal to the user.</p>
			
			<p>If a third party associated with the Akib's News Portal website collects user cookies upon 
			your visit to the Akib's News Portal website, Akib's News Portal does not control the use of these 
			cookies therefore you should check the relevant third-party website.</p>
			
			<h4>Demographic and purchase information:</h4>
			<p>We may reference other sources of demographic and other information to provide you with
			more targeted communications and promotions. We use Google Analytics, among others, to track 
			the user behavior on our website. You can opt-out of Google Analytics for Display Advertising 
			and customize Google Display Network ads using the Ads Settings options provided by Google.
			</p>
			
			<h4>Communication by <i>Akib's News Portal</i></h4>
			<p>From time to time, Akib's News Portal may contact its users via e-mail, phone or SMS for 
			invitation for participation in campaigns/competitions organized by Akib's News Portal, feedback, 
			survey etc, based on the information it had received from the users.</p>
			
			<h4>Accessing the website from outside Bangladesh</h4>
			<p>All personal information submitted by users outside Bangladesh will be processed in 
			accordance with these terms of use and privacy policy.</p>
			
			<h4>Governing Law</h4>
			<p>The laws that govern privacy policy of Akib's News Portal and its relationship with the user 
			is the laws of Bangladesh and any dispute regarding the use, retention, disclosure, leakage 
			or dissemination of the information or date can only be raised before the courts of 
			Bangladesh which shall have exclusive jurisdiction on this matter. The entire privacy policy 
			shall apply to all who enters the website, receives service or uses application from Bengal 
			Gazette regardless of their nationality, location, residence or place of business.</p>
			
			<h4>Modification of Privacy Policy</h4>
			<p><div>Akib's News Portal</div> reserves the right to amend, modify, alter, or omit any terms in the 
			privacy policy at any time but the changed policy shall be immediately uploaded or updated in 
			the website. By continuing to use our services after any changes are made, you accept those 
			changes and will be bound by them. We encourage you to periodically check back and review 
			this policy so that visitors/readers will always know what information we collect, how we use 
			it, and with whom we share it.</p>
			
			<h4>Opt-out</h4>
			<p>If, at any time, the users prefer not to receive email containing marketing information 
			from us, then the user can simply follow the unsubscribe options at the bottom of each email.
			</p>
			
			<p>If the users no longer wish to have a registered account, the user may terminate the 
			account by sending an email to the following address: akib.swe@gmail.com</p>
		</div>
		</div>

		<?php FOOTER(); ?>
	</div>
</body>
</html>